/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myfirstapplication;
import java.sql.*;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;




/**
 *
 * @author mtariqm
 */
public class myFrame1 extends javax.swing.JFrame {
 Connection con=null;
 String gs=null;
 
    /**
     * Creates new form myFrame1
     */
    public myFrame1() {
        initComponents();
         con=conClass.conDB();
         addNodestoTree();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        tablesBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        sTextField = new javax.swing.JTextField();
        sLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jTree1);

        tablesBtn.setText("Tables");
        tablesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablesBtnActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jList1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        Table1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Table1PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(Table1);

        jLabel1.setText("Course ID");

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLabel2");

        jTextField2.setText("jTextField2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField3.setText("jTextField3");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jTextField6.setText("jTextField6");

        jTextField8.setText("jTextField8");

        jTextField7.setText("jTextField7");

        jLabel8.setText("jLabel8");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        sTextField.setText("jTextField9");

        sLabel.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(searchButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(updateButton)
                            .addGap(18, 18, 18)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(printButton)
                            .addGap(17, 17, 17))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2)
                                    .addGap(178, 178, 178))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(71, 71, 71)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(sLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(sTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(searchButton)
                    .addComponent(newButton)
                    .addComponent(printButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(tablesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablesBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (gs=="Faculty"){
         //deleteFacultyDS();
        //deleteFacultySP();
        deleteFacultyRS();
        }
        else if (gs=="Student"){}
    }//GEN-LAST:event_deleteButtonActionPerformed
  private void deleteFacultyRS(){
    int rownum=Table1.getSelectedRow();
    String ID1=Table1.getModel().getValueAt(rownum, 0).toString();
    String sql11="select * from Faculty where faculty_id=?";
      
      try{
      
      
     PreparedStatement pst11=con.prepareStatement(sql11,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
     pst11.setString(1, ID1);
     ResultSet rs11=pst11.executeQuery();
     rs11.absolute(1);
     rs11.deleteRow();
     JOptionPane.showMessageDialog(null,"Record is Deleted");
      }
      catch(Exception e){}
  
  
  
  }
    
    
    
    private void deleteFacultySP(){
   
   int rownum=Table1.getSelectedRow();
    String ID1=Table1.getModel().getValueAt(rownum, 0).toString();
   String sql10="{call spDeleteFaculty(?)}";
     try{
     CallableStatement cst10=con.prepareCall(sql10);
 
    cst10.setString(1, ID1);
   
    cst10.execute();
    JOptionPane.showMessageDialog(null,"Record is Deleted");
     
     }
     catch(Exception e){}
 
 
 
 }
    
    
    private void deleteFacultyDS(){
  String sql9="";
  int numDel=0;
  try{
           int rownum=Table1.getSelectedRow();
           String ID1=Table1.getModel().getValueAt(rownum, 0).toString();
           
           sql9="delete from Faculty where faculty_id=?";
           PreparedStatement pst9=con.prepareStatement(sql9);
           pst9.setString(1, ID1);
          numDel=pst9.executeUpdate();
  
         JOptionPane.showMessageDialog(null,"Record is deleted");
  }
  catch(Exception e){JOptionPane.showMessageDialog(null,"Record is not deleted");}
  
  
  }
    
    
    
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //JTable table=null;
        //table=Table1;
        //String ss=gs;
        //addFacultyRecordIS();
        //addFacultyRecordRS();
         addFacultyRecordSP();
    }//GEN-LAST:event_addButtonActionPerformed
 public void addFacultyRecordSP(){
 int numAdd=0;
 String sql5="{call addFaculty(?,?,?,?,?,?,?)}";
 try{
 CallableStatement cst=con.prepareCall(sql5);
 
    cst.setString(1, jTextField1.getText());
    cst.setString(2, jTextField2.getText()); 
    cst.setString(3, jTextField3.getText());
    cst.setString(4, jTextField4.getText());
    cst.setString(5, jTextField5.getText());
    cst.setString(6, jTextField6.getText());
    cst.setString(7, jTextField7.getText());
    cst.execute();
    System.out.println("Record is added");
 
 }
 catch(Exception e){}
 
 }
 
    public void addFacultyRecordRS(){
    String sql4="select * from Faculty";
    int numAdd=0;
    
    try{
    PreparedStatement pst4=con.prepareStatement(sql4,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
    ResultSet rs4=pst4.executeQuery();
    
     rs4.moveToInsertRow();
     rs4.updateString(1, jTextField1.getText());
     rs4.updateString(2, jTextField2.getText());
     rs4.updateString(3, jTextField3.getText());
     rs4.updateString(4, jTextField4.getText());
     rs4.updateString(5, jTextField5.getText());
     rs4.updateString(6, jTextField6.getText());
     rs4.updateString(7, jTextField7.getText());
     rs4.insertRow();
     rs4.moveToCurrentRow();
          
     System.out.println("Record is added");
    }
    catch(Exception e){}
    
    
    
    
    }
    
    public void addFacultyRecordIS(){
    String sql3="";
    int numAdd=0;
    try{
        sql3="insert into Faculty (faculty_id, faculty_name,office, phone, college, title, email) values(?,?,?,?,?,?,?)";
    PreparedStatement pst3=con.prepareStatement(sql3);
    pst3.setString(1, jTextField1.getText());
    pst3.setString(2, jTextField2.getText()); 
    pst3.setString(3, jTextField3.getText());
    pst3.setString(4, jTextField4.getText());
    pst3.setString(5, jTextField5.getText());
    pst3.setString(6, jTextField6.getText());
    pst3.setString(7, jTextField7.getText());
    
    numAdd = pst3.executeUpdate();
    System.out.println(numAdd);
    
    }
    catch(Exception e){  }
    
    
    
    }
    
    
    
    private void tablesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablesBtnActionPerformed
        //getTables();
        getTablesinComBo();
    }//GEN-LAST:event_tablesBtnActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
       String nd=mySelectedNode();
       gs=nd;
        System.out.println(nd);
        JTable table =null;
        table=Table1;
        showData(table,nd);
              
        
    }//GEN-LAST:event_jTree1ValueChanged

    private void Table1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Table1PropertyChange
        //JTable table=null;
        //table=Table1;
        //String ss=gs;
        //displaySelectedRow1(table,ss);
    }//GEN-LAST:event_Table1PropertyChange

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        JTable table=null;
        table=Table1;
        String ss=gs;
        displaySelectedRow1(table,ss);
    }//GEN-LAST:event_Table1MouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        JTable table=null;
        table=Table1;
        String ss=gs;
        searchRecords(table, ss);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        makeTextFieldsEmpty();
    }//GEN-LAST:event_newButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       //updateFacultyUS();
       //updateFacultyRS();
             
        updateFacultySP();
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
     String ss=gs;
             reportFaculty(ss);
    }//GEN-LAST:event_printButtonActionPerformed
 
    private void reportFaculty(String ss){
    String rp="C:\\Database Programming\\myReport.jrxml";
        try{
        JasperDesign jd=JRXmlLoader.load(rp);
        String sql13="select * from "+ss+" order by faculty_id";
        JRDesignQuery newsql13 = new JRDesignQuery();
        newsql13.setText(sql13);
        jd.setQuery(newsql13);
        
        
        JasperReport report = JasperCompileManager.compileReport(jd);
        JasperPrint myprint= JasperFillManager.fillReport(report, null,con);
        JasperViewer.viewReport(myprint);
        
        }
        catch(Exception e){}
    }
    
    
    
    
    private void updateFacultySP(){
   int numAdd=0;
   int rownum=Table1.getSelectedRow();
    String ID1=Table1.getModel().getValueAt(rownum, 0).toString();
   String sql8="{call spUpdateFaculty(?,?,?,?,?,?,?)}";
      try{
      CallableStatement cst8=con.prepareCall(sql8);
 
    cst8.setString(1, ID1);
    cst8.setString(2, jTextField2.getText()); 
    cst8.setString(3, jTextField3.getText());
    cst8.setString(4, jTextField4.getText());
    cst8.setString(5, jTextField5.getText());
    cst8.setString(6, jTextField6.getText());
    cst8.setString(7, jTextField7.getText());
    cst8.execute();
    JOptionPane.showMessageDialog(null,"Record Updated");
      
      }
      catch(Exception e){}
  
  }
    
    
    private void updateFacultyRS(){
  String sql7="";
    
  try{
    int rownum=Table1.getSelectedRow();
    String ID1=Table1.getModel().getValueAt(rownum, 0).toString();
    sql7="select * from Faculty where faculty_id=?";
    PreparedStatement pst7=con.prepareStatement(sql7,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
    pst7.setString(1, ID1);
    ResultSet rs7=pst7.executeQuery();
    
    if(rs7.absolute(1)){
     
     rs7.updateString(2, jTextField2.getText());
     rs7.updateString(3, jTextField3.getText());
     rs7.updateString(4, jTextField4.getText());
     rs7.updateString(5, jTextField5.getText());
     rs7.updateString(6, jTextField6.getText());
     rs7.updateString(7, jTextField7.getText());
     
     rs7.updateRow();
    JOptionPane.showMessageDialog(null,"Record Updated");
    }
      
  } 
  catch(Exception e){JOptionPane.showMessageDialog(null,"Record not Updated");}
  
  
  }
   private void updateFacultyUS(){
    String sql6="";
    int numUpdate=0;
       
       
       try{
           int rownum=Table1.getSelectedRow();
           String ID1=Table1.getModel().getValueAt(rownum, 0).toString();
           //String ID2 = jTextField1.getText();
           System.out.println(ID1);
           sql6="update Faculty set faculty_name=?, office=?, phone=?, college=?,title=?, email=? where faculty_id=?";
           PreparedStatement pst6=con.prepareStatement(sql6);
           
          pst6.setString(1, jTextField2.getText()); 
         pst6.setString(2, jTextField3.getText());
         pst6.setString(3, jTextField4.getText());
         pst6.setString(4, jTextField5.getText());
         pst6.setString(5, jTextField6.getText());
         pst6.setString(6, jTextField7.getText());
          pst6.setString(7, ID1);
          numUpdate=pst6.executeUpdate();
          JOptionPane.showMessageDialog(null,"Record Updated");
       }
       catch(Exception e){
           
           JOptionPane.showMessageDialog(null,"Record not Updated");}
   
   
   
   }
    
    
    
    public void makeTextFieldsEmpty(){
    
           jTextField1.setText("");
          jTextField2.setText("");
          jTextField3.setText("");
          jTextField4.setText("");
          jTextField5.setText("");
          jTextField6.setText("");
          jTextField7.setText("");
    
    
    }
    public void searchRecords(JTable table, String ss){
        String  sql2="";
        PreparedStatement pstmt2 = null;
        
        
        
  
  try{
          if (sTextField.getText()=="")
        {
              sql2 = "select * from "+ss+"";
               pstmt2=con.prepareStatement(sql2);
        }
             else if(ss=="Faculty" && sTextField.getText()!="")
          {
                sql2 = "select * from "+ss+" where faculty_id=?"; 
                pstmt2=con.prepareStatement(sql2);
              pstmt2.setString(1, sTextField.getText());
           }
           
          ResultSet rs1 =   pstmt2.executeQuery();
          table.setModel(DbUtils.resultSetToTableModel(rs1));
          table.setRowSelectionInterval(0, 0);
          displaySelectedRow1(table,ss);
      }
        catch(Exception e){}
    }
    
    
    public void showData(JTable table, String ss){
  String sql1 = "select * from "+ss+"";
  
  try{
          PreparedStatement pstmt=con.prepareStatement(sql1);
                    
          ResultSet rs = pstmt.executeQuery();
          table.setModel(DbUtils.resultSetToTableModel(rs));
          table.setRowSelectionInterval(0, 0);
          displaySelectedRow1(table,ss);
  
    }
  
  catch(Exception e){}
  
  }
  
  public void displaySelectedRow1(JTable table, String ss){
   if (ss=="Faculty"){
          showFaculty(table);
          }
          else if (ss=="Student"){
          showStudent(table);         
          }
          else if (ss=="Course"){
          showCourse(table);
          
          }   
      
  }
  public void showFaculty(JTable table){
         int selectedRow = table.getSelectedRow();
        
          jTextField1.setText(table.getValueAt(selectedRow, 0).toString());
          jTextField2.setText(table.getValueAt(selectedRow, 1).toString());
          jTextField3.setText(table.getValueAt(selectedRow, 2).toString());
          jTextField4.setText(table.getValueAt(selectedRow, 3).toString());
          jTextField5.setText(table.getValueAt(selectedRow, 4).toString());
          jTextField6.setText(table.getValueAt(selectedRow, 5).toString());
          jTextField7.setText(table.getValueAt(selectedRow, 6).toString());
          
          jLabel1.setText("Faculty_ID");
           jLabel2.setText("Faculty_ID");
            jLabel3.setText("Faculty_ID");
             jLabel4.setText("Faculty_ID");
              jLabel5.setText("Faculty_ID");
               jLabel6.setText("Faculty_ID");
                jLabel7.setText("Faculty_ID");
          
          jTextField8.setVisible(false);
          jLabel8.setVisible(false);
  
  
  }
  
  public void showStudent(JTable table){
         int selectedRow = table.getSelectedRow();
        
          jTextField1.setText(table.getValueAt(selectedRow, 0).toString());
          jTextField2.setText(table.getValueAt(selectedRow, 1).toString());
          jTextField3.setText(table.getValueAt(selectedRow, 2).toString());
          jTextField4.setText(table.getValueAt(selectedRow, 3).toString());
          jTextField5.setText(table.getValueAt(selectedRow, 4).toString());
          jTextField6.setText(table.getValueAt(selectedRow, 5).toString());
          jTextField7.setText(table.getValueAt(selectedRow, 6).toString());
          
          jLabel1.setText("Faculty_ID");
           jLabel2.setText("Faculty_ID");
            jLabel3.setText("Faculty_ID");
             jLabel4.setText("Faculty_ID");
              jLabel5.setText("Faculty_ID");
               jLabel6.setText("Faculty_ID");
                jLabel7.setText("Faculty_ID");
          
          jTextField8.setVisible(false);
          jLabel8.setVisible(false);
  
  
  }
  
  public void showCourse(JTable table){
         int selectedRow = table.getSelectedRow();
        
          jTextField1.setText(table.getValueAt(selectedRow, 0).toString());
          jTextField2.setText(table.getValueAt(selectedRow, 1).toString());
          jTextField3.setText(table.getValueAt(selectedRow, 2).toString());
          jTextField4.setText(table.getValueAt(selectedRow, 3).toString());
          jTextField5.setText(table.getValueAt(selectedRow, 4).toString());
          jTextField6.setText(table.getValueAt(selectedRow, 5).toString());
          jTextField7.setText(table.getValueAt(selectedRow, 6).toString());
          
          jLabel1.setText("Faculty_ID");
           jLabel2.setText("Faculty_ID");
            jLabel3.setText("Faculty_ID");
             jLabel4.setText("Faculty_ID");
              jLabel5.setText("Faculty_ID");
               jLabel6.setText("Faculty_ID");
                jLabel7.setText("Faculty_ID");
          
          jTextField8.setVisible(false);
          jLabel8.setVisible(false);
  
  
  }
  
  
    public String mySelectedNode(){
     //DefaultTreeModel treeModel = (DefaultTreeModel) jTree2.getModel();
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        String ndd=node.getUserObject().toString();
             return ndd;
    
    }
    
    public void getTables(){
       try{
           DatabaseMetaData dbmd = con.getMetaData();
           ResultSet rs2 = dbmd.getTables(null, null, null, new String[] {"TABLE"});
           DefaultListModel myList = new DefaultListModel();
           myList.clear();
                     
          while(rs2.next()){
            myList.addElement(rs2.getString(3));
          //TextArea1.append(rs2.getString(3));
          }
          jList1.setModel(myList);
       
       }
       catch(Exception c){}

  
 }
 
   public void getTablesinComBo(){
       try{
           DatabaseMetaData dbmd = con.getMetaData();
           ResultSet rs2 = dbmd.getTables(null, null, null, new String[] {"TABLE"});
           jComboBox1.removeAll();
           
          while(rs2.next()){
              jComboBox1.addItem(rs2.getString(3));
            
          
          }
                
       }
       catch(Exception c){}

  
 }
      
    public void addNodestoTree(){
    
    DefaultTreeModel treeModel = (DefaultTreeModel) jTree1.getModel();
    DefaultMutableTreeNode root = new DefaultMutableTreeNode("Files");
    DefaultMutableTreeNode tables = new DefaultMutableTreeNode("Tables");
    DefaultMutableTreeNode utilities = new DefaultMutableTreeNode("Utilities");
    DefaultMutableTreeNode reports = new DefaultMutableTreeNode("Reports");
    
    treeModel.setRoot(root);
    root.add(tables);
    root.add(utilities);
    root.add(reports);
    
    DefaultMutableTreeNode t1 = new DefaultMutableTreeNode("Faculty");
    DefaultMutableTreeNode t2 = new DefaultMutableTreeNode("Course");
    DefaultMutableTreeNode t3 = new DefaultMutableTreeNode("Student");
    tables.add(t1);
     tables.add(t2);
      tables.add(t3);
    treeModel.reload();
    
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton newButton;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel sLabel;
    private javax.swing.JTextField sTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton tablesBtn;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
